#!/bin/bash
set -e
echo "Running precompile script..."
echo "ProjectPath: ${ProjectPath:-not set}"
echo "Current directory: $(pwd)"

# Function to find precompile.exe
find_precompile_exe() {
    # Check in current directory
    if [ -f "./precompile.exe" ]; then
        echo "./precompile.exe"
        return 0
    fi
    
    # Check in CDKPath/CSKY/FlashProgrammer/Bins
    if [ -n "${CDKPath}" ] && [ -f "${CDKPath}/CSKY/FlashProgrammer/Bins/precompile.exe" ]; then
        echo "${CDKPath}/CSKY/FlashProgrammer/Bins/precompile.exe"
        return 0
    fi
    
    # Check in relative path from original SDK
    if [ -f "../../../../tools/precompile/Debug/precompile.exe" ]; then
        echo "../../../../tools/precompile/Debug/precompile.exe"
        return 0
    fi
    
    # Check in toolchain bin directory
    if [ -n "${CSKY_TOOLCHAIN}" ] && [ -f "${CSKY_TOOLCHAIN}/precompile.exe" ]; then
        echo "${CSKY_TOOLCHAIN}/precompile.exe"
        return 0
    fi
    
    # Check in PATH
    if command -v precompile.exe >/dev/null 2>&1; then
        echo "precompile.exe"
        return 0
    fi
    
    return 1
}

# Try to find precompile.exe
PRECOMPILE_EXE=$(find_precompile_exe 2>/dev/null || true)

if [ -n "$PRECOMPILE_EXE" ] && [ -f "$PRECOMPILE_EXE" ]; then
    echo "Found precompile.exe at: $PRECOMPILE_EXE"
    # Copy to current directory if not already there
    if [ "$PRECOMPILE_EXE" != "./precompile.exe" ]; then
        cp -v "$PRECOMPILE_EXE" ./precompile.exe || true
    fi
    mkdir -p tmp
    echo "Executing precompile.exe with arguments: ${ProjectPath} $1"
    ./precompile.exe "${ProjectPath}" "$1"
else
    echo "WARNING: precompile.exe not found. Generating minimal __rt_entry.S file."
    # Create a minimal __rt_entry.S file
    cat > "${ProjectPath}/Obj/__rt_entry.S" << 'EOF'
/*
 * Minimal runtime entry for C-Sky CK803
 * Generated by precompile.sh fallback
 */
    .text
    .align  2
    .global __rt_entry
    .type   __rt_entry, %function
__rt_entry:
    /* Branch to main */
    br      main
    .size   __rt_entry, .-__rt_entry
EOF
    echo "Created minimal __rt_entry.S at ${ProjectPath}/Obj/__rt_entry.S"
fi

exit 0
